# Generated by Django 5.0.7 on 2024-07-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='css/media/trade.agile.png', upload_to='css/media/'),
        ),
    ]
