# Generated by Django 5.0.7 on 2024-07-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
