# Generated by Django 5.0.7 on 2024-08-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_remove_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cidcli',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpjcli',
            field=models.CharField(max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codcli',
            field=models.CharField(max_length=10, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='datacli',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estcli',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fonecli',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nomecli',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='razasoccli',
            field=models.CharField(max_length=100, verbose_name='Razão Social'),
        ),
    ]
