# Generated by Django 5.0.7 on 2024-08-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_cliente_imagem_alter_cliente_cidcli_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
